/** Sidebar buttons an admin can hide per user. Checked = hidden. */
export const SIDEBAR_HIDE_OPTIONS: { id: string; label: string }[] = [
  { id: 'company.pupik', label: 'Company — Pupik' },
  { id: 'company.mt', label: 'Company — Monkeytime' },
  { id: 'company.grow', label: 'Company — Grow' },
  { id: 'company.gold', label: 'Company — Goldbug' },
  { id: 'date.range', label: 'Date — From / To' },
  { id: 'date.months', label: 'Date — Months' },
  { id: 'date.openorders', label: 'Date — Open orders' },
  { id: 'date.stock', label: 'Date — Stock' },
  { id: 'view.clients', label: 'View — Clients' },
  { id: 'view.items', label: 'View — Items' },
  { id: 'view.suppliers', label: 'View — Suppliers' },
  { id: 'cat.tablet', label: 'Items — Tablet category' },
  { id: 'cat.group', label: 'Items — Group category' },
  { id: 'clientMode.items', label: 'Clients — Items breakdown' },
  { id: 'clientMode.cash', label: 'Clients — Cash summary' },
  { id: 'itemMode.clients', label: 'Items — By clients' },
  { id: 'itemMode.items', label: 'Items — Items summary' },
  { id: 'supplierMode.items', label: 'Suppliers — Items breakdown' },
  { id: 'supplierMode.cash', label: 'Suppliers — Cash summary' },
]
