-- Capture four tables that were created directly in the Supabase project
-- (out-of-band, never tracked in a migration) so the schema is reproducible
-- from source. These already exist in production; this migration is written
-- idempotently (IF NOT EXISTS / DROP POLICY IF EXISTS) so re-applying it on the
-- live project is a no-op, while a fresh project gets the same shape.
--
-- Written 2026-08-05 while finishing the Supabase cutover (retiring the
-- serverdashboardexcel.xlsm pipeline). Source of truth for the columns/indexes/
-- RLS below is the live project (information_schema + pg_policies dump).
--
--   item_pricing        public price list (list_price, no cost) — parse_pricing
--   item_pricing_admin  admin-only cost per SKU               — parse_pricing
--   receipt_lines       008 collection receipts (net-of-VAT chart) — _sync_receipts
--   debt_meta           per-company debt report date (Debt clients.xlsm B1) — _sync_debt_file_dates

-- ---------------------------------------------------------------------------
-- item_pricing : public list price per SKU/company (upsert key sku,company)
-- ---------------------------------------------------------------------------
create table if not exists public.item_pricing (
  id          bigserial primary key,
  sku         text not null,
  company     text not null,
  name        text,
  supplier_id text,
  list_price  numeric,
  barcode     text,
  synced_at   timestamptz default now(),
  unique (sku, company)
);
alter table public.item_pricing enable row level security;
drop policy if exists item_pricing_select on public.item_pricing;
create policy item_pricing_select on public.item_pricing
  for select using (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------------
-- item_pricing_admin : cost per SKU/company, admin/super_admin read only
-- ---------------------------------------------------------------------------
create table if not exists public.item_pricing_admin (
  id        bigserial primary key,
  sku       text not null,
  company   text not null,
  cost      numeric,
  synced_at timestamptz default now(),
  unique (sku, company)
);
alter table public.item_pricing_admin enable row level security;
drop policy if exists item_pricing_admin_select on public.item_pricing_admin;
create policy item_pricing_admin_select on public.item_pricing_admin
  for select using (
    exists (
      select 1 from public.user_profiles
      where user_profiles.id = auth.uid()
        and user_profiles.role = any (array['admin'::user_role, 'super_admin'::user_role])
    )
  );

-- ---------------------------------------------------------------------------
-- receipt_lines : 008 collection report rows (super-admin only, via SECURITY
-- DEFINER RPC get_dashboard_aux). RLS on, no policy -> only service_role writes
-- and the definer RPC reads; regular clients see nothing directly.
-- ---------------------------------------------------------------------------
create table if not exists public.receipt_lines (
  id             bigint generated by default as identity primary key,
  company        text not null,
  agent_erp_id   text,
  erp_client_id  text not null,
  client_name    text,
  collected_date date not null,
  due_date       date,
  cash_gross     numeric not null default 0,
  synced_at      timestamptz not null default now()
);
create index if not exists receipt_lines_co_month
  on public.receipt_lines using btree (company, collected_date);
alter table public.receipt_lines enable row level security;

-- ---------------------------------------------------------------------------
-- debt_meta : per-company debt report date (Debt clients.xlsm cell B1). RLS on,
-- no policy -> service_role writes, get_dashboard_aux (definer) reads.
-- ---------------------------------------------------------------------------
create table if not exists public.debt_meta (
  company   text primary key,
  file_date date,
  synced_at timestamptz not null default now()
);
alter table public.debt_meta enable row level security;
